---
title: Workflows for mapping agroecological systems using staple food indicator species
author: M.G Walsh, R. Manners, J. Meliyo, and J. Rutembuka
date: "`r format(Sys.time(), '%d, %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    fig_caption: true
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The term ["Cropping system"](https://www.sciencedirect.com/science/article/pii/B9780123948076000241) refers to the crops and crop sequences and management techniques that are used on a given field, farm or region over a period of years. The prevailing ["Agroecological systems"](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/cropping-system) in East Africa are often a direct contrast to the industrial model of agriculture that has reduced labor needs through mechanization, consolidation of farms and fields, and an increased reliance on external agricultural inputs such as fossil fuels, GMOs, improved / patented seed, chemical fertilizers and pesticides. The increased reliance external inputs in turn usually comes at economic, health / nutritional, environmental and/or [Ecosystem service](https://en.wikipedia.org/wiki/Ecosystem_service) costs to smallholder farmers and the associated rural communities. It is not possible to manage the ensuing interactions and complexities without knowing where these agroecological systems are located and how they might be evolving.

*The objective of this notebook is to provide starter code in [R](https://www.r-project.org/) for classifying and spatial mapping of the [Staple food crop systems](https://en.wikipedia.org/wiki/Staple_food) in Rwanda and Tanzania. The observations include: maize, millet, wheat, sorghum, rice, bean, chickpea, pigeon pea, soybean, Irish potatoes, sweet potatoes, cassava and banana, in addition to livestock as well as numerous other, more localized food crops. The markdown notebook presented here is maintained on [Github](), and you can fork and alter it from there for your reference and as you see fit.*

# General data setup

The data we will be using were generated by the [TanSIS]() and [RwaSIS]() projects located in Tanzania and Rwanda respectively. They consist of georeferenced field observations of crops grown in proportion of their national cropland occurrence. The nationally representative cropland sampling frames that are used in the data collections are described in [Walsh et al., (2021)](). 
